### ISSUE TITLE
Implement the meme image div in the main page

### ISSUE THREAD

**Issue by Paresh-95** [Paresh-95/Love_Calculator#1]
Implement meme images in the image div on main page 
I have currently used a static image but it should generate image according to the love percentage he or she got 
Ex -  If love percentage is above 90 then some image is should generate like funny or sarcastic image 
And also add img when user forget to give input or has given partial input 
By default also their should be a image which tells you to give input 

You need to just make it working using sample images once it work i will add images according to my need

**Comment by Mr-Yash-beldar** [comment]
> Implement meme images in the image div on main page I have currently used a static image but it should generate image according to the love percentage he or she got Ex - If love percentage is above 90 then some image is should generate like funny or sarcastic image And also add img when user forget to give input or has given partial input By default also their should be a image which tells you to give input
> 
> You need to just make it working using sample images once it work i will add images according to my need

Assign this to me
